### ISSUE TITLE
Don't automatically install dependancies in `main.py`

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [XInTheDark/mzbot-v2#19]
Automatically installing packages for the user with `os.system` should be avoided, as commands like `pip install -r requirements.txt` aren't guaranteed to work all the time (e.g. if there is more than one version of python installed or `pip` isn't in PATH). Just the `requirements.txt` file is enough to indicate the dependancies and you should tell the user how to install them instead of doing it for them.

**Comment by XInTheDark** [comment]
> Automatically installing packages for the user with `os.system` should be avoided, as commands like `pip install -r requirements.txt` aren't guaranteed to work all the time (e.g. if there is more than one version of python installed or `pip` isn't in PATH). Just the `requirements.txt` file is enough to indicate the dependancies and you should tell the user how to install them instead of doing it for them.

Yes, I'll remove that in next commit, thanks for your kind reminder!
